version: '2'
services:
  eclipse:
    build: "eclipse"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/docker/maven_m2:/home/developer/.m2
      - ~/.gitconfig:/home/developer/.gitconfig
      - ~/docker/git:/home/developer/git
      - ~/docker/eclipse-workspace:/home/developer/eclipse-workspace
    environment:
      - DISPLAY 
